name: Linting, testing , building
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Get repoitory code
        uses: actions/checkout@v3
      - name: Staring Node.js @{{matrix.node-version}}
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}
      - name: install modules
        run: npm ci --force
      - name: build production project
        run: npm run build:prod
      # - name: linting typescript
      #   run: npm run lint:ts
      # - name: linting css
      #   run: npm run lint:css
      # - name: unit testing
      #   run: npm run test:unit
      # - name: build storybook
      #   run: npm run storybook:build
      # - name: screenshot testing
      #   run: npm run test:ui:ci

  test_unit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Get repoitory code
        uses: actions/checkout@v3
      - name: Staring Node.js @{{matrix.node-version}}
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}
      - name: install modules
        run: npm ci --force
      - name: unit testing
        run: npm run test:unit

  lint_ts:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Get repoitory code
        uses: actions/checkout@v3
      - name: Staring Node.js @{{matrix.node-version}}
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}
      - name: install modules
        run: npm ci --force
      - name: linting typescript
        run: npm run lint:ts

  lint_css:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Get repoitory code
        uses: actions/checkout@v3
      - name: Staring Node.js @{{matrix.node-version}}
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}
      - name: install modules
        run: npm ci --force
      - name: linting css
        run: npm run lint:css

  test_screenshot:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Get repoitory code
        uses: actions/checkout@v3
      - name: Staring Node.js @{{matrix.node-version}}
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}
      - name: install modules
        run: npm ci --force
      - name: build storybook
        run: npm run storybook:build
      - name: screenshot testing
        run: npm run test:ui:ci
